bindkey -s ^f "tmux-sessionizer\n"
alias td="tmux detach"
alias ta="tmux attach -t"
alias tls="tmux ls"
alias tn="tmux new"
alias tnw="tmux neww"
alias pnpx="pnpm exec"
alias ggs="git status"
alias gga="git add"
alias ggc="git commit"
alias bfg="java -jar ~/.local/bfg/bfg.jar"
alias kssh="kitty +kitten ssh"
alias ls="ls --color"
