bindkey -s ^f "tmux-sessionizer\n"
alias td="tmux detach"
alias ta="tmux attach -t"
alias tls="tmux ls"
alias tn="tmux new"
alias tnw="tmux neww"
alias pnpx="pnpm exec"
alias gs="git status"
alias ga="git add"
alias gc="git commit"
alias bfg="java -jar ~/.local/bfg/bfg.jar"
alias kssh="kitty +kitten ssh"
alias ls="ls --color"
